# modules/pdf_generator.py
# PDF Generator module using ReportLab.
# Compiles structured meeting minutes JSON into a professional, corporate PDF document.

import os
import time
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from reportlab.pdfgen import canvas
import config

# ==========================================
# Custom Canvas for Dynamic Page Numbering
# ==========================================
class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas renderer to dynamically calculate total pages 
    and draw consistent running headers and footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        # Save state for the second rendering pass
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        # Second pass: draw headers/footers with correct total page count
        page_count = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(page_count)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4B5563")) # Dark Gray
        
        # 1. Top Running Header (draw on page 2 and later)
        if self._pageNumber > 1:
            self.drawString(54, 750, "Minutes of Meeting (MoM)")
            self.setStrokeColor(colors.HexColor("#E5E7EB")) # Light Gray line
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)
            
        # 2. Bottom Running Footer (draw on all pages)
        generation_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        footer_text = f"Generated by AI Meeting Assistant | Powered by Groq + Whisper + ElevenLabs | Date: {generation_time}"
        self.drawString(54, 40, footer_text)
        
        # Draw Right Aligned "Page X of Y"
        page_num_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_num_str)
        
        self.setStrokeColor(colors.HexColor("#E5E7EB"))
        self.setLineWidth(0.5)
        self.line(54, 52, 558, 52)
        
        self.restoreState()

# ==========================================
# Helper Layout Builders
# ==========================================
def make_section_header(title: str, style: ParagraphStyle) -> Table:
    """
    Creates a styled section header flowable with a thick colored bottom border.
    """
    p = Paragraph(f"<b>{title}</b>", style)
    t = Table([[p]], colWidths=[504])
    t.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 1.5, colors.HexColor("#6366F1")), # Indigo bottom line
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
    ]))
    return t

def make_bullet_list(items: list, style: ParagraphStyle) -> list:
    """
    Formats a list of strings into Paragraph bullet flowables.
    """
    elements = []
    for item in items:
        elements.append(Paragraph(f"• {item}", style))
        elements.append(Spacer(1, 4))
    return elements

def make_numbered_list(items: list, style: ParagraphStyle) -> list:
    """
    Formats a list of strings into numbered Paragraph list flowables.
    """
    elements = []
    for i, item in enumerate(items, 1):
        elements.append(Paragraph(f"{i}. {item}", style))
        elements.append(Spacer(1, 4))
    return elements

# ==========================================
# Main PDF Generator Function
# ==========================================
def generate_pdf_report(meeting_data: dict, output_filename: str = None) -> str:
    """
    Generates a structured, styled corporate MoM report PDF from the meeting data dictionary.
    
    Args:
        meeting_data (dict): Dictionary with meeting info, summary, actions, and insights.
        output_filename (str, optional): Custom filename for the output file.
        
    Returns:
        str: Path to the generated PDF file, or a user-friendly error message.
    """
    # 1. Error boundary: Missing data or invalid type
    if not meeting_data or not isinstance(meeting_data, dict):
        return "Error: Invalid or missing meeting data dictionary."
        
    # 2. Setup output directories
    output_dir = os.path.join(config.OUTPUT_DIR, "reports")
    try:
        os.makedirs(output_dir, exist_ok=True)
    except Exception as e:
        return f"Error: Failed to create output directories. Details: {str(e)}"
        
    if not output_filename:
        timestamp = int(time.time())
        output_filename = f"meeting_report_{timestamp}.pdf"
        
    output_path = os.path.join(output_dir, output_filename)
    
    # 3. Safe value extractor (handles missing fields cleanly)
    def get_val(key, default="Not Mentioned"):
        val = meeting_data.get(key)
        if val is None or val == "":
            return default
        return val

    # Extract metadata fields
    meeting_title = get_val("meeting_title", "General Project Alignment")
    meeting_date = get_val("meeting_date", datetime.date.today().strftime("%Y-%m-%d"))
    meeting_dept = get_val("meeting_department", "Not Mentioned")
    meeting_organizer = get_val("meeting_organizer", "Not Mentioned")
    meeting_type = get_val("meeting_type", "Not Mentioned")
    meeting_lang = get_val("meeting_language", "Not Mentioned")
    
    # Extract structural summaries
    exec_summary = get_val("executive_summary", "No executive summary provided.")
    
    # Extract lists (ensure they are lists of strings)
    def get_list(key):
        lst = meeting_data.get(key)
        if not lst or not isinstance(lst, list):
            return ["Not Mentioned"]
        return [str(i) for i in lst]
        
    discussion_points = get_list("discussion_points")
    decisions = get_list("decisions")
    next_steps = get_list("next_steps")
    risks = get_list("risks")
    keywords_list = get_list("keywords")
    
    # Extract insights
    insights = meeting_data.get("insights", {})
    if not isinstance(insights, dict):
        insights = {}
        
    # 4. Setup styles sheet and custom definitions
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        "CoverTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0B0F19"), # Dark Blue
        alignment=0, # Left-aligned
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        "CoverSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#6366F1"), # Indigo Accent
        spaceAfter=15
    )
    
    h1_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#1E1B4B"),
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        "BodyTextDark",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#1F2937"), # Slate Gray
        spaceAfter=8
    )
    
    table_header_style = ParagraphStyle(
        "TableHeaderCell",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=12,
        textColor=colors.white
    )
    
    # 5. Build Flowable Story
    story = []
    
    # cover header
    story.append(Paragraph("AI Meeting Assistant", subtitle_style))
    story.append(Paragraph("Minutes of Meeting (MoM)", title_style))
    story.append(Spacer(1, 10))
    
    # 5.1 Meeting Information Table
    info_data = [
        [Paragraph("<b>Meeting Title:</b>", body_style), Paragraph(meeting_title, body_style)],
        [Paragraph("<b>Meeting Date:</b>", body_style), Paragraph(meeting_date, body_style)],
        [Paragraph("<b>Department:</b>", body_style), Paragraph(meeting_dept, body_style)],
        [Paragraph("<b>Organizer:</b>", body_style), Paragraph(meeting_organizer, body_style)],
        [Paragraph("<b>Meeting Type:</b>", body_style), Paragraph(meeting_type, body_style)],
        [Paragraph("<b>Language:</b>", body_style), Paragraph(meeting_lang, body_style)]
    ]
    info_table = Table(info_data, colWidths=[120, 384])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 15))
    
    # 5.2 Executive Summary
    story.append(make_section_header("1. Executive Summary", h1_style))
    story.append(Spacer(1, 8))
    story.append(Paragraph(exec_summary, body_style))
    story.append(Spacer(1, 12))
    
    # 5.3 Key Discussion Points
    story.append(make_section_header("2. Key Discussion Points", h1_style))
    story.append(Spacer(1, 8))
    story.extend(make_bullet_list(discussion_points, body_style))
    story.append(Spacer(1, 12))
    
    # 5.4 Decisions Made
    story.append(make_section_header("3. Decisions Made", h1_style))
    story.append(Spacer(1, 8))
    story.extend(make_numbered_list(decisions, body_style))
    story.append(Spacer(1, 12))
    
    # 5.5 Action Items (Table)
    story.append(make_section_header("4. Action Items", h1_style))
    story.append(Spacer(1, 8))
    
    action_items = meeting_data.get("action_items")
    action_table_data = [[
        Paragraph("Task Description", table_header_style), 
        Paragraph("Owner", table_header_style), 
        Paragraph("Deadline", table_header_style)
    ]]
    
    if action_items and isinstance(action_items, list):
        for item in action_items:
            if isinstance(item, dict):
                t_desc = item.get("task") or "Not Mentioned"
                t_owner = item.get("owner") or "Not Mentioned"
                t_dl = item.get("deadline") or "Not Mentioned"
                action_table_data.append([
                    Paragraph(t_desc, body_style),
                    Paragraph(t_owner, body_style),
                    Paragraph(t_dl, body_style)
                ])
            else:
                action_table_data.append([Paragraph(str(item), body_style), Paragraph("Not Mentioned", body_style), Paragraph("Not Mentioned", body_style)])
    else:
        action_table_data.append([Paragraph("No action items identified.", body_style), Paragraph("Not Mentioned", body_style), Paragraph("Not Mentioned", body_style)])
        
    action_table = Table(action_table_data, colWidths=[324, 100, 80])
    action_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#6366F1")), # Indigo Accent header
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]), # Zebra striping
    ]))
    story.append(action_table)
    story.append(Spacer(1, 15))
    
    # 5.6 Next Steps & Risks (Kept together if space allows)
    story.append(make_section_header("5. Next Steps", h1_style))
    story.append(Spacer(1, 8))
    story.extend(make_bullet_list(next_steps, body_style))
    story.append(Spacer(1, 12))
    
    story.append(make_section_header("6. Risks & Blockers", h1_style))
    story.append(Spacer(1, 8))
    story.extend(make_bullet_list(risks, body_style))
    story.append(Spacer(1, 12))
    
    # 5.7 Meeting Insights & Keywords
    insights_title = make_section_header("7. Meeting Insights", h1_style)
    insights_data = [
        [Paragraph("<b>Meeting Duration:</b>", body_style), Paragraph(str(insights.get("duration", "Not Mentioned")), body_style),
         Paragraph("<b>Speakers Detected:</b>", body_style), Paragraph(str(insights.get("speakers", "Not Mentioned")), body_style)],
        [Paragraph("<b>Overall Sentiment:</b>", body_style), Paragraph(str(insights.get("sentiment", "Not Mentioned")), body_style),
         Paragraph("<b>AI Confidence:</b>", body_style), Paragraph(str(insights.get("confidence", "Not Mentioned")), body_style)],
        [Paragraph("<b>Productivity Score:</b>", body_style), Paragraph(str(insights.get("productivity", "Not Mentioned")), body_style),
         Paragraph("<b>Est. Reading Time:</b>", body_style), Paragraph(str(insights.get("reading_time", "Not Mentioned")), body_style)]
    ]
    insights_table = Table(insights_data, colWidths=[110, 142, 110, 142])
    insights_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F9FAFB")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#E5E7EB")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    
    keywords_paragraph = Paragraph(f"<b>Keywords:</b> {', '.join(keywords_list)}", body_style)
    
    # Keep insights together to avoid awkward splitting on page break
    story.append(KeepTogether([
        insights_title,
        Spacer(1, 8),
        insights_table,
        Spacer(1, 10),
        keywords_paragraph
    ]))
    
    # 6. Execute PDF build
    try:
        # SimpleDocTemplate uses letter dimensions: 612 x 792 pt
        # Margins are 54 pt (0.75 in), leaving 504 pt of printable width.
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        doc.build(story, canvasmaker=NumberedCanvas)
        return output_path
    except Exception as e:
        return f"Error: PDF generation failed. Details: {str(e)}"

# ==========================================
# Testing / Example Block
# ==========================================
if __name__ == "__main__":
    print("====================================================")
    print("PDF Generator Module - Offline Testing")
    print("====================================================")
    
    # Dummy dictionary representing outputs from llm_processor.py
    sample_data = {
        "meeting_title": "IT Infrastructure Cloud Rollout Plan",
        "meeting_date": "2026-07-03",
        "meeting_department": "Infrastructure & SecOps",
        "meeting_organizer": "Marcus Vance",
        "meeting_type": "Project Review",
        "meeting_language": "English",
        "executive_summary": (
            "The infrastructure committee reviewed milestones for the AWS migration rollout. "
            "All core database targets have successfully completed staging dry runs, and the team approved "
            "the next phase which focuses on routing configurations. The production window is locked."
        ),
        "discussion_points": [
            "AWS VPC configuration and routing tables are completed.",
            "Database load limits were resolved after indexing core audit tables.",
            "Rollback scenarios were reviewed and validated on staging cluster."
        ],
        "decisions": [
            "Migrate staging services to live production domain on August 15th.",
            "Direct billing setups to the new corporate master cost center."
        ],
        "action_items": [
            {"task": "Deploy VPC security groups and update ingress keys", "owner": "Bob Miller", "deadline": "2026-07-10"},
            {"task": "Finalize marketing copy for customer email announcement", "owner": "Alice Carter", "deadline": "2026-08-01"},
            {"task": "Verify staging SSL renewals", "owner": "Not Mentioned", "deadline": "Not Mentioned"}
        ],
        "next_steps": [
            "Perform ingress load testing under simulated peak traffic.",
            "Sync-up call scheduled for next Thursday."
        ],
        "risks": [
            "Potential server latency if egress routes fail to resolve dns fast enough."
        ],
        "insights": {
            "duration": "45 mins",
            "speakers": "4 Speakers",
            "sentiment": "Collaborative",
            "confidence": "97%",
            "productivity": "95/100",
            "reading_time": "3 mins"
        },
        "keywords": ["AWS Migration", "Security Groups", "SSL Renewals", "Load Testing"]
    }
    
    print("\nGenerating sample report PDF...")
    generated_path = generate_pdf_report(sample_data, "test_mom_report.pdf")
    print(f"Result path: {generated_path}")
    if os.path.exists(generated_path):
        print("Success: Generated PDF file verified on disk.")
    else:
        print("Error: Generated file not found.")
